#![doc = include_str!("../README.md")]

mod delete;
mod entity;
mod filter;
mod insert;
mod join;
mod query;
mod select;
mod update;

// The `entity!` expansion names `$crate::anyhow::Result`, so the crate must
// re-export it for callers that do not depend on `anyhow` themselves.
#[doc(hidden)]
pub use anyhow;
pub use delete::DeleteBuilder;
pub use entity::{Entity, EntityValues, FetchValue};
pub use filter::{CmpOp, ColRef, Filter};
pub use insert::{ConflictSet, InsertBuilder, NoConflict};
pub use join::{Join, JoinKind};
pub use omnia_wasi_sql::{DataType, Field, Row};
pub use query::Query;
pub use select::SelectBuilder;
pub use update::UpdateBuilder;

#[doc(hidden)]
pub mod __private {
    pub use sea_query::Value;
}

/// Declares an ORM entity with automatic `Entity` trait implementation.
///
/// # Examples
///
/// ```ignore
/// use omnia_orm::entity;
///
/// entity! {
///     table = "posts",
///     pub struct Post {
///         pub id: i32,
///         pub title: String,
///     }
/// }
/// ```
#[macro_export]
macro_rules! entity {
    // Full form: columns + joins + struct (single code-generation arm)
    (
        table = $table:literal,
        columns = [$( ($col_table:literal, $col_name:literal, $col_field:literal) ),* $(,)?],
        joins = [$($join:expr),* $(,)?],
        $(#[$meta:meta])*
        pub struct $struct_name:ident {
            $(
                $(#[$field_meta:meta])*
                pub $field_name:ident : $field_type:ty
            ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        /// Entity table row generated by [`entity!`].
        pub struct $struct_name {
            $(
                $(#[$field_meta])*
                pub $field_name : $field_type
            ),*
        }

        impl $crate::Entity for $struct_name {
            const TABLE: &'static str = $table;

            fn projection() -> &'static [&'static str] {
                &[ $( stringify!($field_name) ),* ]
            }

            fn joins() -> Vec<$crate::Join> {
                vec![$($join),*]
            }

            fn column_specs() -> Vec<(&'static str, &'static str, &'static str)> {
                vec![$( ($col_field, $col_table, $col_name) ),*]
            }

            fn from_row(row: &$crate::Row) -> $crate::anyhow::Result<Self> {
                Ok(Self {
                    $(
                        $field_name: <$field_type as $crate::FetchValue>::fetch(row, stringify!($field_name))?,
                    )*
                })
            }
        }

        impl $crate::EntityValues for $struct_name {
            fn __to_values(&self) -> Vec<(&'static str, $crate::__private::Value)> {
                vec![
                    $(
                        (stringify!($field_name), self.$field_name.clone().into()),
                    )*
                ]
            }
        }
    };

    // Joins only → forward with empty columns
    (
        table = $table:literal,
        joins = [$($join:expr),* $(,)?],
        $($rest:tt)*
    ) => {
        $crate::entity! {
            table = $table,
            columns = [],
            joins = [$($join),*],
            $($rest)*
        }
    };

    // Bare table → forward with empty columns and joins
    (
        table = $table:literal,
        $($rest:tt)*
    ) => {
        $crate::entity! {
            table = $table,
            columns = [],
            joins = [],
            $($rest)*
        }
    };
}

#[cfg(test)]
pub(crate) mod test_fixtures {
    use super::{Entity, Row};

    /// Minimal two-column entity for builder unit tests.
    pub struct Stop;

    impl Entity for Stop {
        const TABLE: &'static str = "stop";

        fn projection() -> &'static [&'static str] {
            &["stop_id", "name"]
        }

        fn from_row(_row: &Row) -> anyhow::Result<Self> {
            anyhow::bail!("builder tests never map rows")
        }
    }
}
