name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  ci:
    uses: augentic/.github/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      targets: wasm32-wasip2
