name: Create Patch

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  patch:
    uses: augentic/.github/.github/workflows/patch.yaml@v0.2.0
    secrets: inherit
