name: Publish Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  skip:
    name: Skipped
    if: ${{ !startsWith(github.ref_name, 'release-') }}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: |
          echo "This workflow only runs on the 'release-*' branches"
          exit 1

  ci:
    name: CI
    if: ${{ startsWith(github.ref_name, 'release-') }}
    permissions:
      contents: read
    uses: augentic/.github/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      targets: wasm32-wasip2

  publish:
    name: Publish
    needs: ci
    permissions:
      contents: write
    uses: augentic/.github/.github/workflows/publish.yaml@main

  crates:
    name: Publish crates
    needs: publish
    permissions:
      contents: read
    uses: augentic/.github/.github/workflows/crates.yaml@main
    secrets: inherit
