name: Create Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: augentic/.github/.github/workflows/release.yaml@v0.2.0
    secrets: inherit
